import {
  Package, Sparkles, Shirt, Pill, Baby, PawPrint, Milk, Coffee, Wine,
  Snowflake, Apple, Fish, Cookie, UtensilsCrossed, Leaf, Home, Droplets,
  ShoppingBag, Heart, Sandwich, Beef, Wheat, Banana, Citrus, Egg,
  FlaskConical, Flame, Wrench, Star,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const PANTRY_ICON_MAP: Record<string, LucideIcon> = {
  Package,
  Sparkles,
  Shirt,
  Pill,
  Baby,
  PawPrint,
  Milk,
  Coffee,
  Wine,
  Snowflake,
  Apple,
  Fish,
  Cookie,
  UtensilsCrossed,
  Leaf,
  Home,
  Droplets,
  ShoppingBag,
  Heart,
  Sandwich,
  Beef,
  Wheat,
  Banana,
  Citrus,
  Egg,
  FlaskConical,
  Flame,
  Wrench,
  Star,
};

export const PANTRY_ICON_LABELS: Record<string, string> = {
  Package:        "General",
  Sparkles:       "Cleaning",
  Shirt:          "Paper / Laundry",
  Pill:           "Health & Beauty",
  Baby:           "Baby",
  PawPrint:       "Pet",
  Milk:           "Dairy",
  Coffee:         "Beverages",
  Wine:           "Alcohol",
  Snowflake:      "Frozen",
  Apple:          "Produce",
  Fish:           "Seafood",
  Cookie:         "Snacks / Bakery",
  UtensilsCrossed:"Pantry Staples",
  Leaf:           "Organic / Natural",
  Home:           "Household",
  Droplets:       "Liquid / Spray",
  ShoppingBag:    "Other",
  Heart:          "Personal Care",
  Sandwich:       "Deli / Prepared",
  Beef:           "Meat",
  Wheat:          "Bread / Grain",
  Banana:         "Fruit",
  Citrus:         "Citrus",
  Egg:            "Eggs",
  FlaskConical:   "Chemical",
  Flame:          "Spices / Sauces",
  Wrench:         "Hardware",
  Star:           "Favourite",
};

export function getPantryIcon(name: string): LucideIcon {
  return PANTRY_ICON_MAP[name] ?? Package;
}
